on:
  push:
    branches:
      - main
    # paths:
    #   - '*'
    #   - '!README.md'
    #   - '!main.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: npm ci
      - name: Testing
        run: npm test

  build-deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_CREDENTIALS }}
      SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_EMAIL }}
      SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup the cloud SDK using community built action
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        # Sets environment variables
        with:
          project_id: $PROJECT_ID
          service_account_key: $SERVICE_ACCOUNT_KEY
          service_account_email: $SERVICE_ACCOUNT_EMAIL

      - name: Build
        run: gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Deploy
        run: >
          gcloud run deploy
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          --port 8080
          --platform managed
          --region europe-west1
          --allow-unauthenticated
