name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: npm ci

      - name: Testing
        run: npm test

  build-deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          service_account_email: ${{ secrets.GCP_EMAIL }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container to GCR
        run: |-
          docker build --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:$GITHUB_SHA" .
          docker push "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:$GITHUB_SHA"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ secrets.GCP_SERVICE_NAME }}
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:$GITHUB_SHA
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          region: europe-west1

  # build-deploy:
  #   needs: test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     # Setup the cloud SDK using community built action
  #     - name: Setup Cloud SDK
  #       uses: google-github-actions/setup-gcloud@v0.2.0
  #       # Sets environment variables
  #       with:
  #         project_id: ${{ secrets.GCP_PROJECT_ID }}
  #         service_account_key: ${{ secrets.GCP_CREDENTIALS }}
  #         service_account_email: ${{ secrets.GCP_EMAIL }}

  #     - name: Build
  #       run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:$GITHUB_SHA

  #     - name: Deploy
  #       run: >
  #         gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }}
  #         --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_SERVICE_NAME }}:$GITHUB_SHA
  #         --port 8080
  #         --platform managed
  #         --region europe-west1
  #         --allow-unauthenticated
